// backend/Data-info/courses-data.js - Backend course data storage

// Add this majors array at the very top
const majors = [
  "Computer Science",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Engineering",
  "Business Administration",
  "Psychology",
];

const coursesData = {
  "Computer Science": [
    {
      id: "CS101",
      name: "Introduction to Programming",
      credits: 3,
      cost: 300,
      instructor: "Dr. Smith",
      schedule: "Mon/Wed 9:00-10:30",
      enrolled: 85,
      capacity: 120,
      rating: 4.5,
      reviews: 127,
      description:
        "Learn fundamental programming concepts using Python and algorithm design",
      prerequisites: [],
      syllabus: [
        "Variables and Data Types",
        "Control Structures",
        "Functions",
        "Object-Oriented Programming",
      ],
      department: "Computer Science",
      semester: "Fall 2024",
      room: "CS Building 101",
    },
    {
      id: "CS102",
      name: "Data Structures and Algorithms",
      credits: 4,
      cost: 350,
      instructor: "Prof. Johnson",
      schedule: "Tue/Thu 11:00-12:30",
      enrolled: 75,
      capacity: 100,
      rating: 4.3,
      reviews: 89,
      description:
        "Advanced programming concepts, data structures, and algorithm optimization",
      prerequisites: ["CS101"],
      syllabus: [
        "Arrays and Linked Lists",
        "Stacks and Queues",
        "Trees and Graphs",
        "Sorting Algorithms",
        "Hash Tables",
      ],
      department: "Computer Science",
      semester: "Fall 2024",
      room: "CS Building 203",
    },
    {
      id: "CS201",
      name: "Web Development Fundamentals",
      credits: 3,
      cost: 320,
      instructor: "Dr. Wilson",
      schedule: "Mon/Wed/Fri 2:00-3:00",
      enrolled: 65,
      capacity: 90,
      rating: 4.6,
      reviews: 156,
      description:
        "HTML, CSS, JavaScript, and modern web development frameworks",
      prerequisites: ["CS101"],
      syllabus: [
        "HTML5 and CSS3",
        "JavaScript ES6+",
        "React.js",
        "Node.js",
        "Database Integration",
      ],
      department: "Computer Science",
      semester: "Fall 2024",
      room: "CS Building 305",
    },
    {
      id: "CS301",
      name: "Database Systems",
      credits: 4,
      cost: 380,
      instructor: "Dr. Chen",
      schedule: "Tue/Thu 1:00-2:30",
      enrolled: 55,
      capacity: 80,
      rating: 4.4,
      reviews: 92,
      description:
        "Database design, SQL, NoSQL, and database management systems",
      prerequisites: ["CS102"],
      syllabus: [
        "Relational Database Design",
        "SQL Programming",
        "NoSQL Databases",
        "Database Optimization",
        "Transactions",
      ],
      department: "Computer Science",
      semester: "Fall 2024",
      room: "CS Building 201",
    },
    {
      id: "CS401",
      name: "Machine Learning Fundamentals",
      credits: 4,
      cost: 420,
      instructor: "Prof. Anderson",
      schedule: "Mon/Wed 3:30-5:00",
      enrolled: 45,
      capacity: 60,
      rating: 4.8,
      reviews: 73,
      description:
        "Introduction to machine learning algorithms and data science",
      prerequisites: ["CS102", "MATH201"],
      syllabus: [
        "Supervised Learning",
        "Unsupervised Learning",
        "Neural Networks",
        "Deep Learning",
        "Model Evaluation",
      ],
      department: "Computer Science",
      semester: "Fall 2024",
      room: "CS Building 401",
    },
  ],

  Mathematics: [
    {
      id: "MATH101",
      name: "Calculus I",
      credits: 4,
      cost: 320,
      instructor: "Dr. Wilson",
      schedule: "Mon/Wed/Fri 8:00-9:00",
      enrolled: 95,
      capacity: 150,
      rating: 4.2,
      reviews: 156,
      description:
        "Differential and integral calculus fundamentals with applications",
      prerequisites: [],
      syllabus: [
        "Limits and Continuity",
        "Derivatives",
        "Applications of Derivatives",
        "Integrals",
        "Applications of Integration",
      ],
      department: "Mathematics",
      semester: "Fall 2024",
      room: "Math Building 101",
    },
    {
      id: "MATH102",
      name: "Calculus II",
      credits: 4,
      cost: 320,
      instructor: "Prof. Taylor",
      schedule: "Tue/Thu 9:30-11:00",
      enrolled: 78,
      capacity: 120,
      rating: 4.1,
      reviews: 134,
      description: "Advanced integration techniques, sequences, and series",
      prerequisites: ["MATH101"],
      syllabus: [
        "Integration Techniques",
        "Improper Integrals",
        "Sequences and Series",
        "Parametric Equations",
        "Polar Coordinates",
      ],
      department: "Mathematics",
      semester: "Fall 2024",
      room: "Math Building 102",
    },
    {
      id: "MATH201",
      name: "Linear Algebra",
      credits: 3,
      cost: 300,
      instructor: "Dr. Martinez",
      schedule: "Mon/Wed/Fri 11:00-12:00",
      enrolled: 62,
      capacity: 100,
      rating: 4.5,
      reviews: 98,
      description:
        "Vector spaces, matrices, eigenvalues, and linear transformations",
      prerequisites: ["MATH101"],
      syllabus: [
        "Vector Spaces",
        "Matrix Operations",
        "Determinants",
        "Eigenvalues and Eigenvectors",
        "Linear Transformations",
      ],
      department: "Mathematics",
      semester: "Fall 2024",
      room: "Math Building 201",
    },
    {
      id: "MATH301",
      name: "Statistics and Probability",
      credits: 3,
      cost: 310,
      instructor: "Prof. Davis",
      schedule: "Tue/Thu 2:00-3:30",
      enrolled: 71,
      capacity: 90,
      rating: 4.3,
      reviews: 112,
      description:
        "Probability theory, statistical inference, and data analysis",
      prerequisites: ["MATH102"],
      syllabus: [
        "Probability Distributions",
        "Statistical Inference",
        "Hypothesis Testing",
        "Regression Analysis",
        "ANOVA",
      ],
      department: "Mathematics",
      semester: "Fall 2024",
      room: "Math Building 301",
    },
  ],

  Physics: [
    {
      id: "PHYS101",
      name: "Physics I - Mechanics",
      credits: 4,
      cost: 340,
      instructor: "Dr. Thompson",
      schedule: "Mon/Wed/Fri 10:00-11:00",
      enrolled: 88,
      capacity: 120,
      rating: 4.4,
      reviews: 145,
      description: "Classical mechanics, motion, forces, energy, and momentum",
      prerequisites: ["MATH101"],
      syllabus: [
        "Kinematics",
        "Newton's Laws",
        "Work and Energy",
        "Momentum",
        "Rotational Motion",
      ],
      department: "Physics",
      semester: "Fall 2024",
      room: "Physics Building 101",
    },
    {
      id: "PHYS102",
      name: "Physics II - Electricity & Magnetism",
      credits: 4,
      cost: 340,
      instructor: "Prof. Rodriguez",
      schedule: "Tue/Thu 8:30-10:00",
      enrolled: 67,
      capacity: 100,
      rating: 4.2,
      reviews: 98,
      description:
        "Electric fields, magnetic fields, circuits, and electromagnetic waves",
      prerequisites: ["PHYS101", "MATH102"],
      syllabus: [
        "Electric Charge and Fields",
        "Electric Potential",
        "Current and Resistance",
        "Magnetic Fields",
        "Electromagnetic Induction",
      ],
      department: "Physics",
      semester: "Fall 2024",
      room: "Physics Building 102",
    },
  ],

  Chemistry: [
    {
      id: "CHEM101",
      name: "General Chemistry I",
      credits: 4,
      cost: 330,
      instructor: "Dr. Lee",
      schedule: "Mon/Wed/Fri 9:00-10:00",
      enrolled: 92,
      capacity: 130,
      rating: 4.3,
      reviews: 167,
      description: "Atomic structure, chemical bonding, and stoichiometry",
      prerequisites: [],
      syllabus: [
        "Atomic Structure",
        "Periodic Table",
        "Chemical Bonding",
        "Molecular Geometry",
        "Stoichiometry",
      ],
      department: "Chemistry",
      semester: "Fall 2024",
      room: "Chemistry Building 101",
    },
    {
      id: "CHEM102",
      name: "General Chemistry II",
      credits: 4,
      cost: 330,
      instructor: "Prof. Wang",
      schedule: "Tue/Thu 1:30-3:00",
      enrolled: 76,
      capacity: 110,
      rating: 4.1,
      reviews: 134,
      description:
        "Thermodynamics, kinetics, equilibrium, and electrochemistry",
      prerequisites: ["CHEM101"],
      syllabus: [
        "Thermodynamics",
        "Chemical Kinetics",
        "Chemical Equilibrium",
        "Acid-Base Chemistry",
        "Electrochemistry",
      ],
      department: "Chemistry",
      semester: "Fall 2024",
      room: "Chemistry Building 102",
    },
  ],

  Biology: [
    {
      id: "BIO101",
      name: "Introduction to Biology",
      credits: 3,
      cost: 290,
      instructor: "Dr. Garcia",
      schedule: "Tue/Thu 10:00-11:30",
      enrolled: 80,
      capacity: 100,
      rating: 4.6,
      reviews: 114,
      description:
        "Cell biology, genetics, evolution, and ecological principles",
      prerequisites: [],
      syllabus: [
        "Cell Structure and Function",
        "Genetics",
        "Evolution",
        "Ecology",
        "Biodiversity",
      ],
      department: "Biology",
      semester: "Fall 2024",
      room: "Biology Building 101",
    },
    {
      id: "BIO201",
      name: "Human Anatomy and Physiology",
      credits: 4,
      cost: 350,
      instructor: "Prof. Brown",
      schedule: "Mon/Wed 1:00-2:30",
      enrolled: 65,
      capacity: 80,
      rating: 4.5,
      reviews: 87,
      description: "Structure and function of human body systems",
      prerequisites: ["BIO101", "CHEM101"],
      syllabus: [
        "Skeletal System",
        "Muscular System",
        "Nervous System",
        "Cardiovascular System",
        "Respiratory System",
      ],
      department: "Biology",
      semester: "Fall 2024",
      room: "Biology Building 201",
    },
  ],

  Engineering: [
    {
      id: "ENG101",
      name: "Engineering Fundamentals",
      credits: 3,
      cost: 350,
      instructor: "Dr. Miller",
      schedule: "Mon/Wed/Fri 8:00-9:00",
      enrolled: 78,
      capacity: 100,
      rating: 4.3,
      reviews: 123,
      description: "Introduction to engineering principles and problem-solving",
      prerequisites: ["MATH101"],
      syllabus: [
        "Engineering Design Process",
        "Technical Communication",
        "Engineering Ethics",
        "Problem Solving",
        "Team Projects",
      ],
      department: "Engineering",
      semester: "Fall 2024",
      room: "Engineering Building 101",
    },
    {
      id: "ENG201",
      name: "Statics and Dynamics",
      credits: 4,
      cost: 380,
      instructor: "Prof. Johnson",
      schedule: "Tue/Thu 11:00-12:30",
      enrolled: 56,
      capacity: 75,
      rating: 4.2,
      reviews: 89,
      description: "Analysis of forces in static and dynamic systems",
      prerequisites: ["ENG101", "PHYS101"],
      syllabus: [
        "Force Systems",
        "Equilibrium",
        "Structural Analysis",
        "Kinematics",
        "Kinetics",
      ],
      department: "Engineering",
      semester: "Fall 2024",
      room: "Engineering Building 201",
    },
  ],

  "Business Administration": [
    {
      id: "BUS101",
      name: "Introduction to Business",
      credits: 3,
      cost: 280,
      instructor: "Dr. Adams",
      schedule: "Mon/Wed/Fri 1:00-2:00",
      enrolled: 95,
      capacity: 140,
      rating: 4.4,
      reviews: 187,
      description:
        "Overview of business fundamentals and corporate environment",
      prerequisites: [],
      syllabus: [
        "Business Environment",
        "Management Principles",
        "Marketing Basics",
        "Financial Fundamentals",
        "Business Ethics",
      ],
      department: "Business Administration",
      semester: "Fall 2024",
      room: "Business Building 101",
    },
    {
      id: "BUS201",
      name: "Principles of Marketing",
      credits: 3,
      cost: 300,
      instructor: "Prof. Clark",
      schedule: "Tue/Thu 9:00-10:30",
      enrolled: 82,
      capacity: 110,
      rating: 4.5,
      reviews: 156,
      description:
        "Marketing strategies, consumer behavior, and market analysis",
      prerequisites: ["BUS101"],
      syllabus: [
        "Marketing Mix",
        "Consumer Behavior",
        "Market Research",
        "Digital Marketing",
        "Brand Management",
      ],
      department: "Business Administration",
      semester: "Fall 2024",
      room: "Business Building 201",
    },
  ],

  Psychology: [
    {
      id: "PSY101",
      name: "Introduction to Psychology",
      credits: 3,
      cost: 270,
      instructor: "Dr. White",
      schedule: "Mon/Wed/Fri 11:00-12:00",
      enrolled: 103,
      capacity: 150,
      rating: 4.7,
      reviews: 198,
      description: "Overview of psychological principles and human behavior",
      prerequisites: [],
      syllabus: [
        "History of Psychology",
        "Research Methods",
        "Learning and Memory",
        "Personality",
        "Abnormal Psychology",
      ],
      department: "Psychology",
      semester: "Fall 2024",
      room: "Psychology Building 101",
    },
    {
      id: "PSY201",
      name: "Developmental Psychology",
      credits: 3,
      cost: 290,
      instructor: "Prof. Green",
      schedule: "Tue/Thu 2:30-4:00",
      enrolled: 67,
      capacity: 90,
      rating: 4.6,
      reviews: 124,
      description: "Human development from conception through adulthood",
      prerequisites: ["PSY101"],
      syllabus: [
        "Prenatal Development",
        "Childhood Development",
        "Adolescence",
        "Adult Development",
        "Aging",
      ],
      department: "Psychology",
      semester: "Fall 2024",
      room: "Psychology Building 201",
    },
  ],
};

// Store for registered students (in a real app, this would be a database)
const students = [
  // Example student data - will be populated as students register
  {
    id: 1,
    studentId: "STU001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    major: "Computer Science",
    registeredCourses: [
      {
        id: "CS101",
        name: "Introduction to Programming",
        credits: 3,
        cost: 300,
        major: "Computer Science",
        enrollmentDate: "2024-09-01T10:00:00Z",
      },
    ],
    totalCredits: 3,
    totalCost: 300,
    registrationDate: "2024-09-01T09:30:00Z",
    status: "registered",
    completionDate: "2024-09-01T10:30:00Z",
  },
];

// Helper functions
const getCourseById = (courseId) => {
  for (const [major, courses] of Object.entries(coursesData)) {
    const course = courses.find((c) => c.id === courseId);
    if (course) {
      return { course, major };
    }
  }
  return null;
};

const getStudentByStudentId = (studentId) => {
  return students.find((s) => s.studentId === studentId);
};

const getMajorDescription = (major) => {
  const descriptions = {
    "Computer Science":
      "Master the art of programming, software development, and cutting-edge technology solutions.",
    Mathematics:
      "Explore the beauty of numbers, equations, and mathematical reasoning that powers our world.",
    Biology:
      "Discover the fascinating world of living organisms and the science of life.",
    Physics:
      "Understand the fundamental laws that govern our universe and natural phenomena.",
    Chemistry:
      "Dive into the molecular world and learn how matter transforms at the atomic level.",
    Engineering:
      "Design, build, and innovate solutions to real-world problems through applied science.",
    "Business Administration":
      "Develop leadership skills and business acumen for the corporate world.",
    Psychology:
      "Explore the human mind, behavior, and the complexities of mental processes.",
  };
  return descriptions[major] || "Explore this exciting field of study.";
};
/*
export {
  coursesData,
  students,
  getCourseById,
  getStudentByStudentId,
  getMajorDescription,
};
*/

module.exports = {
  majors, // 👈 ADD THIS LINE
  coursesData,
  students,
  getCourseById,
  getStudentByStudentId,
  getMajorDescription,
};
